### ISSUE TITLE
Golang compiler regression for some arm64-v8a devices

### ISSUE THREAD

**Issue by FoxP** [x0b/rcx#58] opened 2020-05-02 09:57 UTC
Hello,

Unlocking my configuration file works with `v1.10.2`, but not with `v1.11.3.167` (Google Play version).

I noticed that the rclone version is "`-1`" for `v1.11.3.167`. So i guess that's the issue.
Tried `Google Play` version, but also `rcx-v1.11.3-universal-release.apk` from github repo.

Old versions from https://github.com/kaczmarkiewiczp/rcloneExplorer work perfectly.

- Bad rclone version : 

![Screenshot_20200502-114441](https://user-images.githubusercontent.com/16615901/80860960-a83a3e00-8c6b-11ea-9ff9-1ca7e499babe.png)

- Error message :

![Screenshot_20200502-114507](https://user-images.githubusercontent.com/16615901/80860961-a96b6b00-8c6b-11ea-9288-a14a7ec5dfb5.png)

#### Technical Information

```
rclone: -1
rcloneExplorer: 1.11.3
android-sdk: 23
android-device: Redmi Note 3
android-ndk-abis: arm64-v8a;armeabi-v7a;armeabi
```

**Comment by x0b** [comment] 2020-05-02 12:04
Thank you for reporting this with details. 

You are quite right about the ```-1```. It will appear when the rclone binary is not compatible with your phone.  There might be a packaging or distribution error, e.g. you received an APK for the wrong CPU type.

Could you attach/send the APK you installed/received via Google Play?  

And, if possible, enable logs and (Settings > Logging > ), force-close the app and then restart it. If the binary logs something before crashing, the log file will be located on the external storage directory ```Android/data/io.github.x0b.rcx/files```. Could you also send that in (to [x0bdev@gmail.com](mailto:x0bdev@gmail.com) if you don't want to post this publicly)?

**Comment by FoxP** [comment] 2020-05-02 12:35
- Apk received via Google Play : [base.zip](https://github.com/x0b/rcx/files/4567688/base.zip)
- Log file : [log.txt](https://github.com/x0b/rcx/files/4567689/log.txt)

Please note that i use [Aurora Store](https://gitlab.com/AuroraOSS/AuroraStore) as Google Play alternative. My phone is running [LineageOS](https://forum.xda-developers.com/redmi-note-3/development/rom-lineageos-13-0-t3533744).

**Comment by FoxP** [comment] 2020-05-03 06:19
OK, same issue with `rcx-v1.11.3-arm64-v8a-release.apk`, but `rcx-v1.11.3-armeabi-v7a-release.apk` works. :+1:

**Comment by FoxP** [comment] 2020-05-03 10:29
That's weird, Google Play version is more up-to-date than Github release :

![Screenshot_20200503-122642-picsay](https://user-images.githubusercontent.com/16615901/80911900-8c9d6900-8d39-11ea-89b5-f289b41b5551.png)

**Comment by x0b** [comment] 2020-05-03 13:50
Okay, so from the log files it seems that the golang compiler is not compatible with LineageOS. Would you be available for questions and tests if I create an issue with golang?

> OK, same issue with rcx-v1.11.3-arm64-v8a-release.apk, but rcx-v1.11.3-armeabi-v7a-release.apk works. 👍

I was going to ask you to try this out - it will probably a bit slower though, since the CPU has to emulate armv7. But at least it is a possible fallback option.

> That's weird, Google Play version is more up-to-date than Github release :

Is this from the "Aurora Store"? I think I know what is happening here. Aurora seems to display the versionCode field as part of the version. Since you have installed the ```armeabi-v7a``` version (166), Aurora thinks that the ```arm64-v8a``` version (167) is an update. That is not true - the last digit does not matter, it only signifies the CPU architecture. 

Normally, Aurora would be right - this line from your report means that you device prefers 64-bit ```arm64-v8a```, but offers 32-bit ```armeabi-v7a``` and the really old ```armeabi``` in case the newer one is not available.
>#### Technical Information
>
>```
>android-ndk-abis: arm64-v8a;armeabi-v7a;armeabi
>```

So for this work properly again, we need to figure out why golang ```arm64-v8a``` builds don't work here.

**Comment by FoxP** [comment] 2020-05-03 15:11
> Okay, so from the log files it seems that the golang compiler is not compatible with LineageOS. Would you be available for questions and tests if I create an issue with golang?

No problem, i'll be happy to help solving this issue. Since it was working with older builds i hope it may be easy to fix.

> Is this from the "Aurora Store"? 

Yes.

**Comment by x0b** [comment] 2020-05-07 21:02
It doesn't seem like Golang is spending much time investigating this.

Would you be able to execute a few tests over adb? And if yes, on which OS (Windows/Linux/Mac)?

**Comment by FoxP** [comment] 2020-05-08 07:00
Oh. 
No problem, on Windows.

**Comment by x0b** [comment] 2020-05-08 17:09
Okay, plug your phone into your computer and make sure that adb works.

Download and extract [this test script zip files](https://send.firefox.com/download/ba70399724ab2859/#khQakPrjTdLRk1zYtvJIUg). 

Then, run the ```test.cmd``` from the extracted zip and attach the generated log file. 

If you have security concerns, check the test script before you run it by opening it with a text editor.

**Comment by FoxP** [comment] 2020-05-10 12:10
Here is my log file : [log.txt](https://github.com/x0b/rcx/files/4605610/log.txt)
I had to use ADB over Wi-Fi since Windows was not able to find my device from USB.

**Comment by x0b** [comment] 2020-05-10 18:43
Great, this should give us a few pointers to start. 

We will now try to narrow down the specific problem - we will probably need your help again to execute more tests.

**Comment by x0b** [comment] 2020-05-12 18:59
Could you help us out again? We have a new test. As with the last one, please execute the test and then attach the log.txt.

[rcx-debug-58-test-2.zip](https://github.com/x0b/rcx/files/4617828/rcx-debug-58-test-2.zip)

BTW: If you want to follow the discussion on Golang, it is in https://github.com/golang/go/issues/38838.

**Comment by FoxP** [comment] 2020-05-14 18:25
Here log file for test 2 : [log.txt](https://github.com/x0b/rcx/files/4630212/log.txt)
This one was (very) fast to deploy / run.

**Comment by x0b** [comment] 2020-05-14 20:45
Yeah, it seems I forgot to add a flag 🙄. I've repackaged everything, and added a few more tests just in case we're right. However, it might also be the case that we are currently further away from a resolution than initially thought. 

Could you please try it again? 

https://send.firefox.com/download/44c8c9dff6575ada/#yK74phMsBEzdUicUueEFEw

**Comment by FoxP** [comment] 2020-05-16 08:26
No problem, here is log file for test 3 : [log.txt](https://github.com/x0b/rcx/files/4638041/log.txt)

**Comment by x0b** [comment] 2020-05-16 18:41
Great :)

Btw, the newly released version 1.11.4 should work for you as well, but I'm still searching for a permanent solution.

**Comment by FoxP** [comment] 2020-05-17 07:38
Updated with Aurora Store : new version is working great ! :)
Thanks for your time and support on this issue.

**Comment by x0b** [comment] 2020-05-17 21:35
No problem. 

I do have to ask you for another test, if that is okay. I used a different phone model as stand-in that shows the same error. Could you maybe execute this final test? Then I know that I have actually Identified the correct issue.

https://send.firefox.com/download/51bdeee1aa84bd1e/#Bx_IgNZ9PFIGt-b-IJcIxw

**Comment by FoxP** [comment] 2020-05-18 06:30
No problem. Here is log file : [log.txt](https://github.com/x0b/rcx/files/4642367/log.txt)

**Comment by x0b** [comment] 2020-05-18 18:55
Thank you for your continued help :)

We have now confirmed the affected version precisely, and I hope it is soon solved for good.

**Comment by FoxP** [comment] 2020-05-19 06:09
Good news !
You did an amazing job. :)

**Comment by x0b** [comment] 2020-05-26 20:13
I've worked with golang to create a fix, and [my PR](https://github.com/golang/go/pull/39217) has been merged now. 

Thank you, you played an important role in figuring out what exactly went wrong. Fixing bugs in a programming language itself doesn't happen every day.

Be sure to open a new issue if something else comes up.

**Comment by FoxP** [comment] 2020-05-30 07:34
Indeed, this golang issue was not trivial : Good job!
Thanks for your time! Happy to have been able to help you.

**Closed** 2021-03-12 21:04 UTC
Labels: Priority: P2, 🐞 Bug
