### ISSUE TITLE
Detect PDF files and guess their mime types on encrypted remotes

### ISSUE THREAD

**Issue by fieryflamon** [x0b/rcx#136] opened 2021-05-09 19:25 UTC
https://github.com/GrapheneOS/PdfViewer/issues/91

Trying to directly view pdfs in encrypted folders in rclone creates a "Cannot open file with invalid MIME type" error.

#### What version of RCX are you using (About -> App version)?
1.12.0

#### What is your Android version, phone model and manufacturer?
Pixel 4a, grapheneos

#### Which steps are required to reproduce this issue?
Opening a pdf on an encrypted remote

#### Does the same issue also occur when using the same configuration on a PC or in Termux?
No

#### What are the contents of ```Android/data/io.github.x0b.rcx/files/logs/log.txt```?
<details><summary><code>log.txt</code> (click to expand) </summary><br><pre>

None

</pre></details>

**Comment by fieryflamon** [comment] 2021-05-09 19:29
Workaround: Open as text works

**Comment by x0b** [comment] 2021-05-10 07:38
I cannot reproduce this, it works just fine on Android. In general, encrypted files don't reveal much metadata, and RCX downloads the file and then asks the system deal with it. If GrapheneOS has changed or removed features that are required for this, there is not much that RCX can do.

Here's how the intent looks, if you want to take this to GrapheneOS' maintainers:
```
action: android.intent.action.VIEW
data: content://io.github.x0b.fileprovider/cache/filename
```

**Comment by thenktor** [comment] 2021-05-19 18:44
> Workaround: Open as text works

Same here on Graphene OS.

**Comment by x0b** [comment] 2021-07-05 16:21
I recently got newer devices and tested this there as well with no problems; these are Android One devices. 

I'm going to close this now since I cannot reproduce this issue on stock Android. If the people over at @GrapheneOS want to provide a custom Intent spec or even a patch that's fine, but until then there's nothing we can do on our side.

**Comment by thestinger** [comment] 2021-07-05 16:41
This has nothing to do with GrapheneOS but rather this app was / is sending the intent with the wrong mime type to our PDF Viewer app. The app is not specific to GrapheneOS. You're confusing a project being under our namespace with it only being relevant to our OS. The issue filed here is making a similar mistake.

**Comment by x0b** [comment] 2021-07-05 18:28
🤷‍♂️ if it doesn't reproduce on stock Android with any of the apps that we may have installed - which include the Google PDF Viewer, the Google Drive PDF viewer, the OneDrive viewer, the Microsoft word viewer, various print plugins - then it is an issue in with the component people are running on their phones.

> [**thestinger** commented on 9 May](https://github.com/GrapheneOS/PdfViewer/issues/91#issuecomment-835881018)
> You'll need to report this bug in their app to them, not to us.

This sounded like you were sending people to the RCX issue tracker. We investigated this and found no problems with stock Android components. 

> You're confusing a project being under our namespace with it only being relevant to our OS. 

Sorry for misunderstanding, it seemed like the PDF Viewer with the problem was associated with GrapheneOS.

Although this works as intended on stock Android with all the apps with tested, we'd still be interested in an exact Intent spec for the Intent that this PDF Viewer component needs. Whatever project this PDF viewer belongs to, it really doesn't matter to us. Though we'd really prefer if we didn't have to introduce special-case code for defective third party apps.

**Comment by thestinger** [comment] 2021-07-06 13:54
Again, this has nothing to do with 'stock Android' (which is not a specific OS and is only made by Google for Pixel phones) vs. GrapheneOS.

**Comment by thestinger** [comment] 2021-07-06 13:56
Our PDF Viewer is not a defective app. I'm no longer interested in talking to you due to you making false claims and spreading misinformation about GrapheneOS. Stop spreading FUD. You don't want to take the time to understand the problem? Fine.

**Comment by thestinger** [comment] 2021-07-06 14:47
The error message clearly explains the problem:

> Cannot open file with invalid MIME type

The app only handles `application/pdf`. It's the only mime type listed for the intent. If you pass something with a different mime type set, it will produce an error. I think that's quite straightforward.

**Comment by x0b** [comment] 2021-07-06 16:30
Let's not break out into needless accusations. On RCX, we may discuss fiercely about technical aspects, but we always treat each other with respect. If someone has issues with that, they will be shown the door.

> The app only handles application/pdf. It's the only mime type listed for the intent. If you pass something with a different mime type set, it will produce an error.

That is actually helpful. What I think happens is that RCX cannot determine the mime type (due to the file being encrypted) and sends the file with a general mime type (`!= application/pdf`). [Taking a peek at the PDF Viewer source code](https://github.com/GrapheneOS/PdfViewer/blob/ce254aecc0bb3fc41908dc6150dc26dd6f775926/app/src/main/java/org/grapheneos/pdfviewer/PdfViewer.java#L288), the app seems to reject any file where the mime type isn't exactly `application/pdf`.

Now, since we work for our users, we did investigate if we can reconstruct mime types from other clues. For example, the [PDF file format](https://en.wikipedia.org/wiki/PDF) seems to be easily recognizable by the magic `%PDF`. I think we'll find some place to squeeze that in. I guess all the other PDF readers do something similar when they receive a file from RCX.

**Comment by thestinger** [comment] 2021-07-06 16:52
> Let's not break out into needless accusations. On RCX, we may discuss fiercely about technical aspects, but we always treat each other with respect. If someone has issues with that, they will be shown the door.

You've done anything but treat us with respect. You're calling our app defective and have been incredibly rude while spreading misinformation about GrapheneOS and the PDF Viewer app.

> Now, since we work for our users, we did investigate if we can reconstruct mime types from other clues. For example, the PDF file format seems to be easily recognizable by the magic %PDF. I think we'll find some place to squeeze that in. I guess all the other PDF readers do something similar when they receive a file from RCX.

If you don't know the mime type if `application/pdf`, why are you passing it to a program accepting only `application/pdf`?

The app is checking that what it was passed matches the API contract as a sanity check. You're violating the API contract. It *only* accepts `application/pdf`. If you don't know it's a PDF, why are you passing it to our app? You need to be detecting file types in order to determine which apps you can pass them to. There are standard file type / mime type handling libraries. You need generic mime type detection, not something specific to PDFs. You can detect mime types from file extensions and/or magic numbers. Either way, you should only be offering to open a file in apps that are compatible with the mime type. It's broken to pass something other than application/pdf to PDF Viewer. It's not the responsibility of PDF Viewer to detect the mime type. The caller is supposed to set it. That's the API contract. Look at what's in the PDF Viewer manifest. It only accepts application/pdf.

**Comment by x0b** [comment] 2021-07-06 17:49
No one in the RCX community is spreading any misinformation in this thread. We investigated the situation, found no issues with all the popular readers apps, and reported this as such. We also said:

> Though we'd really prefer if we didn't have to introduce special-case code for defective third party apps.

Without specifically referring to any particular app, because well, this is a general problem and not limited to a particular app. 
We have special case code for VLC and some other file management apps, and having to create and maintain those hacks is not a good idea.

> If you don't know it's a PDF, why are you passing it to our app?

"you" as in RCX? RCX doesn't. RCX starts the Intent, and the system shows a target app chooser to the user. I have no idea why the system allows selecting the PDF Viewer in that case.

RCX does not strive for being technically right, we like things that work and result in a good UX for our users. And if we can make some users happy by improving our PDF handling code, we'll do it.


---

This is my final answer on this matter.

**Further accusations or abrasive behaviour towards RCX users or contributors will be removed from this thread and may result in a ban.**

Technical aspects or implementation concerns for the new feature are of course still welcome.

---

**Comment by thestinger** [comment] 2021-07-06 17:57
> RCX does not strive for being technically right, we like things that work and result in a good UX for our users. And if we can make some users happy by improving our PDF handling code, we'll do it.

As I said above, you should have generic mime type detection. It doesn't make sense to do something specific to PDFs.

You've been spreading misinformation and repeatedly insulting our project. You're accusing me of being abrasive when you started with these attacks. If you can't be honest about that, fine. Stop making attacks on our project and against me.

**Closed** 2021-07-09 15:36 UTC
Labels: Priority: P3, ✨ Enhancement
